name: Push (main)

on:
  push:
    branches:
      - main
    paths:
      - "rockcraft.yaml"
      - ".github/workflows/**.yaml"

jobs:
  build:
    uses: ./.github/workflows/build-rock.yaml
  publish:
    needs: build
    uses: ./.github/workflows/publish.yaml
